name: kog-ticketbot

services:
  postgres:
    container_name: kog-ticketbot-postgres
    image: postgres
    restart: always
    ports:
      - 127.0.0.1:${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql